name: Fork Sync Develop

on:
  schedule:
    - cron: '0 3,9,15,21 * * *' # every 6 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-20.04

    steps:
      - uses: tgymnich/fork-sync@v1.5
        with:
          pr_title: Fork Sync Deleop
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: cocoa-mhlw
          base: develop
          head: develop
          auto_approve: true
