name: Fork Sync

on:
  schedule:
    - cron: '0 0,6,12,18 * * *' # every 6 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-20.04

    steps:
      - uses: tgymnich/fork-sync@v1.5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: cocoa-mhlw
          base: main
          head: main
          auto_approve: true
